---
title: "Shiller Cyclically Adjusted PE"
author: "Rob Hayward"
date: "Saturday, October 04, 2014"
output: html_document
---

# Notes on Shiller's Cyclically Adjusted PE #
These initial ideas from [Wikipedia](http://en.wikipedia.org/wiki/Cyclically_adjusted_price-to-earnings_ratio).  CAPE is the price per the average of 10 year of earnings adjusted for inflation. This can be thought of as one way to trying to implement the ideaS of Benhamine Graham and David Dodd.  The Intellegent Investor. It takes the long term view and tries to ignore the noisy fluctuations of earnings. Shiller 

There are criticisms. For example, [Jeremy Siegel, writing in the FT](http://www.ft.com/cms/s/0/496a3844-0013-11e3-9c40-00144feab7de.html?siteedition=uk#axzz3FBnqBfeg) argues that accounting changes have adversely affected earnings and cause the measure pait a pessimistic picture.   THe reciprocal of the PE ratio is the earnings yield.  This may be used to compare to bond yields as another method of analysis.  This is controversial.  Some people suggest that real and nominal variables should not be compared.  

*Irrational Exhubirance*.  Greenspan used the term on December 1996.  Norbert Keimling has found similar effects for other markets.  

## The Fed Model## 
The Fed model compares the stock market's earnings yield (E/P) to the yield on long-term government bonds. Some versions suggest that there is equilibrium when the one-year forward earnings yield is equal to the 10-year note yield. 

$$\frac{E}{P} = Y_{10}$$

Greenspan refers to the link between the fall in the real yield on fixed income that occured since 1990 and the increase in the P/E ratio and return on housing. The broad idea is that there are competing assets. It may also be argued that the goverment bond is an estimate of the risk-free rate that will can be used to discount future earnings. The correlation between the bond yield and the PE is high in the 1995-2002 period.  However, it is less reliable outside this time. Look at the data. 

There is less support for this model in other markets and some criticism of the model from academic sources.  CAPE seems to be much better at predicting the future.  There is an argument that investors set prices based on nominal rather than real interest rates.  This is money illusion. 